services:
  app:
    build:
      context: .
      dockerfile: ./d/ts.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    env_file:
      - .env
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/usr/src/app
      - ./db/todo.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

